## This file is a template, and might need editing before it works on your project.
#---
## image
#image: swr.cn-north-4.myhuaweicloud.com/codechina/vuepress:latest
#
##image: vuepress:latest
#
##before_script:
##  - apk add --update --no-cache git
#
##variables:
##  GIT_SUBMODULE_STRATEGY: recursive
#
#pages:
#  script:
##    - apt update
##    - apt-get install curl sudo dirmngr apt-transport-https lsb-release ca-certificates -y
##    - curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
##    - apt install nodejs -y
#    - export NODE_OPTIONS=--max_old_space_size=4096
#    - npm config set registry https://registry.npm.taobao.org
#    - npm install -g vuepress
#    - vuepress build docs -d public
#  artifacts:
#    paths:
#      - public
#  only:
#    - master
#  tags:
#    - pages
